language: java
jdk: openjdk8

env:
  - GRADLE_VERSION=6.8.3
  - GRADLE_VERSION=7.0
  - GRADLE_VERSION=7.0.1-20210430041714+0000

install: skip
script:
  - ./gradlew wrapper --gradle-version=$GRADLE_VERSION
  - ./gradlew checkstyleMain --scan
